# -*- coding: utf-8 -*-
import argparse
import asyncio
import json
import os
from typing import Any, Dict, List, Optional

import aiohttp
import numpy as np
import regex as re
from datasets import load_dataset

try:
    from math_verify.errors import TimeoutException
    from math_verify.metric import math_metric
    from math_verify.parser import ExprExtractionConfig, LatexExtractionConfig
except ImportError:
    raise ImportError("Please install math-verify: pip install math-verify")

# Replace with your URL, we used modelscope
API_URL = "https://api-inference.modelscope.cn/v1/chat/completions"


def compute_score(model_output: str, ground_truth: str, timeout_score: float = 0.0) -> float:
    """Verify whether model_output matches ground_truth using math-verify."""
    verify_func = math_metric(
        gold_extraction_target=(LatexExtractionConfig(),),
        pred_extraction_target=(ExprExtractionConfig(), LatexExtractionConfig()),
    )
    if "boxed" not in ground_truth:
        ground_truth = "\\boxed{" + ground_truth + "}"
    try:
        score, _ = verify_func([ground_truth], [model_output])
        return float(score)
    except TimeoutException:
        return timeout_score
    except Exception:
        return 0.0


async def stream_llm_response(
    session: aiohttp.ClientSession,
    prompt: str,
    args: argparse.Namespace,
    mode: str = "think",
):
    """Stream API response. For think mode, automatically wrap reasoning with <think> and </think>."""
    headers = {
        "Authorization": f"Bearer {args.api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "messages": [{"content": prompt, "role": "user"}],
        "model": args.model_name,
        "max_tokens": args.max_tokens,
        "temperature": args.temperature,
        "top_p": args.top_p,
        "stream": True,
    }

    sign = [True, True]  # for think mode: [reasoning_started, content_started]

    try:
        async with session.post(API_URL, json=payload, headers=headers) as response:
            if response.status != 200:
                yield f"Error: HTTP {response.status}"
                return

            buffer = ""
            async for chunk in response.content:
                buffer += chunk.decode("utf-8")
                while "\n" in buffer:
                    line, buffer = buffer.split("\n", 1)
                    line = line.strip()
                    if line.startswith("data:"):
                        data = line[5:].strip()
                        if data == "[DONE]":
                            return
                        try:
                            json_data = json.loads(data)
                            delta = json_data["choices"][0]["delta"]
                            reasoning_content = delta.get("reasoning_content", "")
                            content = delta.get("content", "")

                            if mode == "think":
                                if reasoning_content:
                                    if sign[0]:
                                        reasoning_content = "<think>\n" + reasoning_content
                                        sign[0] = False
                                    yield reasoning_content
                                elif content:
                                    if sign[1]:
                                        content = "\n</think>\n" + content
                                        sign[1] = False
                                    yield content
                            else:  # no_think
                                if content:
                                    yield content
                        except Exception:
                            continue
    except Exception as e:
        yield f"Error: {str(e)}"


async def call_model(
    session: aiohttp.ClientSession,
    prompt: str,
    args: argparse.Namespace,
    mode: str = "think",
) -> str:
    """Collect all chunks from stream_llm_response into a single string."""
    chunks = []
    async for chunk in stream_llm_response(session, prompt, args, mode):
        chunks.append(chunk)
    return "".join(chunks)


async def process_item(
    session: aiohttp.ClientSession,
    item: Dict[str, Any],
    semaphore: asyncio.Semaphore,
    args: argparse.Namespace,
) -> Optional[Dict[str, Any]]:
    """Process a single problem: get pre-solution, generate full reasoning, verify, format."""
    async with semaphore:
        problem = item["problem"]
        answer = item["answer"]

        # ---------- 1. Obtain pre-solution ----------
        # Non-thinking responses can be generated by other models
        pre_solution = item.get("qwen_no_think")
        if not pre_solution:
            no_think_prompt = (
                f"# Problem:\n{problem}\n\n"
                f"Please answer the problem step by step, and put your final answer within \\boxed{{}}./no_think"
            )
            pre_solution = await call_model(session, no_think_prompt, args, mode="no_think")
            if not pre_solution or "boxed{" not in pre_solution:
                return None

        # Extract final answer part of pre-solution
        if "</think>" in pre_solution:
            pre_part = pre_solution.split("</think>")[-1]
        else:
            pre_part = pre_solution

        if "boxed{" not in pre_part:
            return None

        # ---------- 2. Generate full reasoning in thinking mode ----------
        think_prompt = (
            f"# Problem:\n{problem}\n\n"
            f"# Pre-solution: \n{pre_solution.lstrip()}\n\n"
            f"Please refer to the pre-solution to answer the problem "
            f"and put your final correct answer within \\boxed{{}}."
        )
        re_completion = await call_model(session, think_prompt, args, mode="think")
        if not re_completion or "<think>" not in re_completion or "</think>" not in re_completion:
            return None

        # ---------- 3. Verify final answer ----------
        final_part = re_completion.split("</think>")[-1]
        if "boxed{" not in final_part:
            return None
        final_score = compute_score(final_part, answer)
        if final_score != 1.0:
            return None

        # ---------- 4. Verify pre-solution ----------
        pre_score = compute_score(pre_part, answer)
        pre_correct = (pre_score == 1.0)

        # ---------- 5. Build SFT response ----------
        pre_content = pre_part.lstrip()
        pre_content = pre_content.replace("Final Answer", "Pre Answer").replace(
            "final answer", "pre answer"
        )

        # Remove the leading <think> from re_completion, keep the rest
        re_completion_clean = "".join(re_completion.split("<think>"))

        response = (
            f"<think>\n\n"
            f"<pre>\n# Pre-solution: \n{pre_content}\n</pre>\n\n"
            f"{re_completion_clean.lstrip()}"
        )

        return {
            "problem": problem,
            "response": response,
            "pre_correct": pre_correct,
        }


async def main():
    parser = argparse.ArgumentParser(description="Generate final SFT data for Rethinker.")
    parser.add_argument("--input_file", type=str, required=True,
                        help="Input JSONL/Parquet file with 'problem' and 'answer' fields.")
    parser.add_argument("--output_file", type=str, required=True,
                        help="Output JSONL file for SFT data.")
    parser.add_argument("--api_key", type=str, required=True,
                        help="ModelScope API key.")
    parser.add_argument("--model_name", type=str, default="Qwen/Qwen3-235B-A22B",
                        help="Generator model name.")
    parser.add_argument("--concurrency", type=int, default=5,
                        help="Concurrent API requests.")
    parser.add_argument("--max_tokens", type=int, default=8192,
                        help="Max tokens for generation.")
    parser.add_argument("--temperature", type=float, default=0.6,
                        help="Temperature.")
    parser.add_argument("--top_p", type=float, default=0.95,
                        help="Top-p.")
    parser.add_argument("--max_pre_correct", type=int, default=None,
                        help="Max number of pre-correct samples to keep. None = all.")
    parser.add_argument("--max_pre_wrong", type=int, default=None,
                        help="Max number of pre-wrong samples to keep. None = all.")
    args = parser.parse_args()

    # Load data
    if args.input_file.endswith((".json", ".jsonl")):
        dataset = load_dataset("json", data_files=args.input_file)["train"]
    else:
        dataset = load_dataset("parquet", data_files=args.input_file)["train"]

    items = [dict(row) for row in dataset]
    print(f"Loaded {len(items)} problems.")

    semaphore = asyncio.Semaphore(args.concurrency)
    async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=600)) as session:
        tasks = [process_item(session, item, semaphore, args) for item in items]
        results = await asyncio.gather(*tasks)

    # Write final SFT data
    pre_correct_count = 0
    pre_wrong_count = 0
    with open(args.output_file, "w", encoding="utf-8") as f:
        for res in results:
            if res is None:
                continue
            if res["pre_correct"]:
                if args.max_pre_correct is not None and pre_correct_count >= args.max_pre_correct:
                    continue
                pre_correct_count += 1
            else:
                if args.max_pre_wrong is not None and pre_wrong_count >= args.max_pre_wrong:
                    continue
                pre_wrong_count += 1

            f.write(json.dumps({
                "problem": res["problem"],
                "response": res["response"],
            }, ensure_ascii=False) + "\n")

    print(f"Done. Saved {pre_correct_count} pre-correct and {pre_wrong_count} pre-wrong samples.")
    print(f"Output: {args.output_file}")


if __name__ == "__main__":
    asyncio.run(main())
